#
# Copyright © 2020 PyInstaller Development Team
#
# This file is part of PyInstaller Hook Sample.
#
# PyInstaller Hook Sample is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# PyInstaller Hook Sample is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PyInstaller Hook Sample. If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

language: python
python: 3.7
dist: xenial

branches:
  except:
    - /pyup\/.*/

install:
  # We need pip>=18.0 to handle the extra requirements below.
  - python -m pip install 'pip>=18.0'
  # When installing, include dependencies needed to run tests.
  - pip install .[test]

script:
  # Run test the suite of our package. (Here we use pytest, but of
  # course you might use any other way to run the tests.)
  - pytest tests/test_basic.py
